# Generated by Django 3.1.3 on 2020-11-25 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotShape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('-created_at', '-updated_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_capacity', models.IntegerField(default=10)),
                ('booked_capacity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('slot_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.slotshape')),
            ],
            options={
                'ordering': ('-created_at', '-updated_at'),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
