# Generated by Django 3.1.3 on 2020-11-25 14:58

from django.db import migrations
from datetime import time

def add_slot_shapes(apps, schema_editor):
    SlotShape = apps.get_model('slots', 'SlotShape')
    morning_slot = SlotShape.objects.update_or_create(label='AM', start_time=time(9, 0), end_time=time(12, 0))
    afternoon_slot = SlotShape.objects.update_or_create(label='PM', start_time=time(12, 0), end_time=time(17, 0))
    evening_slot = SlotShape.objects.update_or_create(label='EVE', start_time=time(17, 0), end_time=time(20, 0))

class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_slot_shapes)
    ]
