# Generated by Django 3.1.3 on 2020-11-25 15:27

from django.db import migrations
from dateutil.rrule import DAILY, rrule
import datetime


def add_eight_weeks_of_slots(apps, schema_editor):
    Slot = apps.get_model('slots', 'Slot')
    SlotShape = apps.get_model('slots', 'SlotShape')

    morning_slot_shape, created = SlotShape.objects.get_or_create(label='AM', start_time=datetime.time(9, 0), end_time=datetime.time(12, 0))
    afternoon_slot_shape, created = SlotShape.objects.get_or_create(label='PM', start_time=datetime.time(12, 0), end_time=datetime.time(17, 0))
    evening_slot_shape, created = SlotShape.objects.get_or_create(label='EVE', start_time=datetime.time(17, 0), end_time=datetime.time(20, 0))

    for date in rrule(DAILY, dtstart=datetime.datetime.now(), until=datetime.datetime.now() + datetime.timedelta(weeks=8)):
        morning_slot = Slot(date=date, slot_shape=morning_slot_shape)
        morning_slot.save()
        afternoon_slot = Slot(date=date, slot_shape=afternoon_slot_shape)
        afternoon_slot.save()
        evening_slot = Slot(date=date, slot_shape=evening_slot_shape)
        evening_slot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_add_slot_shape_data'),
    ]

    operations = [
        migrations.RunPython(add_eight_weeks_of_slots)
    ]
